version: '2'
volumes:
  node_modules:

services:
  arangodb:
    image: "arangodb:3.2"
    ports:
      - "8529:8529"
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - "./db-data:/var/lib/arangodb3/:rw"
  redis:
    image: "redis:3.2-alpine"
    ports:
      - "6379:6379"
